[project]
name = "wazobia-embed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jsonlines>=4.0.0",
    "ollama>=0.4.7",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "tiktoken>=0.9.0",
]
