[project]
name = "wazobia-embed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.5.1",
    "gdown>=5.2.0",
    "jsonlines>=4.0.0",
    "numpy>=2.2.4",
    "ollama>=0.4.8",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "tiktoken>=0.9.0",
]
